package br.unirio.pcs.suta.ui;

import br.unirio.pcs.dao.ObraDAO;
import br.unirio.pcs.dao.PedidoDAO;
import br.unirio.pcs.suta.Obra;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeMath.round;

/**
 *
 * @author Lucas
 * @author Tiago
 */
public class CarrinhoTela extends javax.swing.JFrame {

    private List<Obra> obras;

    /**
     * Creates new form Carrinho
     */
    public CarrinhoTela() {
        initComponents();

        try {
            this.listObra();
            this.mostrarTotal();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * Mostra a soma dos itens no carrinho.
     */
    public void mostrarTotal() {
        ObraDAO ob = new ObraDAO();
        double total = 0;
        double total_arr = 0;
        try {
            this.obras = ob.listarObras();
            for (Obra obra : obras) {

                total += obra.getPreco();
            }

            total_arr = Math.round(total * 100.0) / 100.0;
            String total_convertido = String.valueOf(total_arr);
            this.totalCompra.setText(total_convertido);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     *
     * Metodo publico que vai chamar o list obra passando um nome como
     * parâmetro.
     */
    public void listObra() {

        try {
            this.listObraEspecifica();
        } catch (Exception ex) {
            Logger.getLogger(CarrinhoTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     *
     * @throws Exception
     */
    private void listObraEspecifica() throws Exception { // TODO: Passar um nome especifico de uma obra para ser adicionada.

        ObraDAO ob = new ObraDAO();
        this.obras = ob.listarObras();
        DefaultTableModel model = (DefaultTableModel) visuPedidoTabela.getModel();

        for (int i = 0; i < obras.size(); i++) {

            Object rowData[] = new Object[3];
            rowData[0] = obras.get(i).getNome();
            rowData[1] = obras.get(i).getAutor();
            rowData[2] = obras.get(i).getPreco();

            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        visuPedidoDescricao = new javax.swing.JLabel();
        visuPedidoPane = new javax.swing.JScrollPane();
        visuPedidoTabela = new javax.swing.JTable();
        visuPedidoProsseguir = new javax.swing.JButton();
        visuPedidoCancelar = new javax.swing.JButton();
        visuPedidoVoltar = new javax.swing.JButton();
        totalCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visuPedidoDescricao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        visuPedidoDescricao.setText("Seu Pedido no momento:");

        visuPedidoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Livro", "Autor", "Preço por unidade"
            }
        ));
        visuPedidoPane.setViewportView(visuPedidoTabela);

        visuPedidoProsseguir.setText("Prosseguir com pedido");
        visuPedidoProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoProsseguirActionPerformed(evt);
            }
        });

        visuPedidoCancelar.setText("Cancelar pedido");
        visuPedidoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoCancelarActionPerformed(evt);
            }
        });

        visuPedidoVoltar.setText("Voltar ao catalogo");
        visuPedidoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoVoltarActionPerformed(evt);
            }
        });

        totalCompra.setEditable(false);

        jLabel1.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(visuPedidoVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(visuPedidoCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(visuPedidoProsseguir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(visuPedidoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(visuPedidoDescricao)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(visuPedidoDescricao)
                .addGap(38, 38, 38)
                .addComponent(visuPedidoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visuPedidoProsseguir)
                    .addComponent(visuPedidoCancelar)
                    .addComponent(visuPedidoVoltar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVisuPedidoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoCancelarActionPerformed
        // TODO add your handling code here:
        CarrinhoTela cancelar = new CarrinhoTela();
        this.dispose();
        cancelar.setVisible(true);
    }//GEN-LAST:event_botaoVisuPedidoCancelarActionPerformed

    private void botaoVisuPedidoProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoProsseguirActionPerformed
        // TODO add your handling code here:
        FormEnderecoTela prosseguiu = new FormEnderecoTela();
        ObraDAO ob = new ObraDAO();
        double total = 0;
        double total_arr = 0;
        try {
            this.obras = ob.listarObras();
            for (Obra obra : obras) {

                total += obra.getPreco();

                total_arr = Math.round(total * 100.0) / 100.0;        
                prosseguiu.setTotalPedido(total_arr);
                this.dispose();
                prosseguiu.setVisible(true);

            }
        } catch (Exception ex) {
            Logger.getLogger(CarrinhoTela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botaoVisuPedidoProsseguirActionPerformed

    private void botaoVisuPedidoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoVoltarActionPerformed
        // TODO add your handling code here:
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoVisuPedidoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField totalCompra;
    private javax.swing.JButton visuPedidoCancelar;
    private javax.swing.JLabel visuPedidoDescricao;
    private javax.swing.JScrollPane visuPedidoPane;
    private javax.swing.JButton visuPedidoProsseguir;
    private javax.swing.JTable visuPedidoTabela;
    private javax.swing.JButton visuPedidoVoltar;
    // End of variables declaration//GEN-END:variables
}
