package br.unirio.pcs.suta.ui;

import br.unirio.pcs.dao.ObraDAO;
import br.unirio.pcs.suta.CatalogoObra;
import br.unirio.pcs.suta.Obra;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lombok.*;
/**
 *
 * @author Lucas
 * @author Tiago
 */
public class CatalogoTela extends javax.swing.JFrame {

    @Getter
    private List<Obra> obras;
    private String nomeObra;

    /**
     * Creates new form Catalogo
     */
    public CatalogoTela() throws Exception {

        initComponents();
        this.listObra();
        this.addListener();
    }

    CatalogoTela(String text) {

    }
    /**
     *
     * Método que lista as obras disponíveis no catálogo
     *
     * @throws Exception
     */
    public void listObra() throws Exception {

        ObraDAO ob = new ObraDAO();
        this.obras = ob.listarObras();
        DefaultTableModel model = (DefaultTableModel) catalogoTabela.getModel();

        for (int i = 0; i < obras.size(); i++) {

            Object rowData[] = new Object[3];
            rowData[0] = obras.get(i).getNome();
            rowData[1] = obras.get(i).getAutor();
            rowData[2] = obras.get(i).getPreco();
            model.addRow(rowData);
        }
    }

    /**
     * Método que adiciona um Listener na Tabela para mostrar o produto
     *
     */
    public void addListener() {

        catalogoTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) { //Adiciona o evento de duplo click do mouse

                    LinhaMouseClicked(evt);
                }
            }
        });
    }
    /**
     * Método que mostra os detalhes do Produto
     *
     * @param evt
     */
    public void LinhaMouseClicked(java.awt.event.MouseEvent evt) {
        // get the selected row
        int index = catalogoTabela.getSelectedRow();
        TableModel model = catalogoTabela.getModel();
        ResumoLivroTela resumo = new ResumoLivroTela(); // Instancia a classe que apresenta o resumo do livro.
        List<Obra> obra;
        ObraDAO dao = new ObraDAO();

        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        StringBuffer sb = new StringBuffer();
        String lineSeparator = System.getProperty("line.separator");

        sb.append(model.getValueAt(index, 0).toString() + lineSeparator);
        sb.append(model.getValueAt(index, 1).toString() + lineSeparator);
        //sb.append(model.getValueAt(index, 2).toString() + lineSeparator);
        try {
            
            obra = dao.consultarObraPeloNome(model.getValueAt(index, 0).toString());
            for (Obra ob : obra) {
                sb.append(ob.getSinopse() + lineSeparator);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // Chama o metodo que vai colocar o resumo em um JTextArea da classe ResumoLivroTela
        resumo.MostraResumo(sb.toString());
        resumo.setVisible(true);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogoPane = new javax.swing.JScrollPane();
        catalogoTabela = new javax.swing.JTable();
        catalogoSugerirObras = new javax.swing.JButton();
        catalogoVoltar = new javax.swing.JButton();
        catalogoDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        catalogoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro", "Autor", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogoPane.setViewportView(catalogoTabela);
        if (catalogoTabela.getColumnModel().getColumnCount() > 0) {
            catalogoTabela.getColumnModel().getColumn(0).setResizable(false);
            catalogoTabela.getColumnModel().getColumn(1).setResizable(false);
            catalogoTabela.getColumnModel().getColumn(2).setResizable(false);
        }

        catalogoSugerirObras.setText("Sugerir Obras para adição no catálogo");
        catalogoSugerirObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCatalogoSugerirObrasActionPerformed(evt);
            }
        });

        catalogoVoltar.setText("Voltar a Tela Inicial");
        catalogoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCatalogoVoltarActionPerformed(evt);
            }
        });

        catalogoDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        catalogoDescricao.setText("Catálogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogoSugerirObras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(catalogoVoltar)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(catalogoDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(catalogoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogoDescricao)
                .addGap(13, 13, 13)
                .addComponent(catalogoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catalogoSugerirObras)
                    .addComponent(catalogoVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCatalogoSugerirObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCatalogoSugerirObrasActionPerformed
        MsgSugerirLivroTela msgSugestao = new MsgSugerirLivroTela();
        this.dispose();
        msgSugestao.setVisible(true);
    }//GEN-LAST:event_botaoCatalogoSugerirObrasActionPerformed

    private void botaoCatalogoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCatalogoVoltarActionPerformed
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoCatalogoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new CatalogoTela().setVisible(true);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catalogoDescricao;
    private javax.swing.JScrollPane catalogoPane;
    private javax.swing.JButton catalogoSugerirObras;
    private javax.swing.JTable catalogoTabela;
    private javax.swing.JButton catalogoVoltar;
    // End of variables declaration//GEN-END:variables
}
